msapconfig:
  greeting: "hello"
  
---

spring:
  profiles: local

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/

msapconfig:
  greeting: "welcome to local server"

---

spring:
  profiles: dev

msapconfig:
  greeting: "welcome to dev server"

---

spring:
  profiles: test
  
msapconfig:
  greeting: "welcome to test server"

---

spring:
  profiles: staging
  
msapconfig:
  greeting: "welcome to staging server"

---

spring:
  profiles: prod
  
msapconfig:
  greeting: "welcome to prod server"