msapconfig:
  greeting: "hello"
  db:
    ip: aaa
    port: bbb

---

spring:
  profiles: local

msapconfig:
  greeting: "welcome to local server"
  db:
    ip: AAAA
    port: bbbb

---

spring:
  profiles: dev

msapconfig:
  greeting: "welcome to dev server"

---

spring:
  profiles: staging
  
msapconfig:
  greeting: "welcome to staging server"

---

spring:
  profiles: prod
  
msapconfig:
  greeting: "welcome to prod server"

