msapconfig:
  greeting: "hello"
  db:
    ip: 192.168.0.16
    port: 9999

---

spring:
  profiles: local

msapconfig:
  greeting: "welcome to local server"
  db:
    ip: 192.168.0.16
    port: 9999

---

spring:
  profiles: dev

msapconfig:
  greeting: "welcome to dev server"
  db:
    ip: 192.168.0.16
    port: 9999

---

spring:
  profiles: staging
  
msapconfig:
  greeting: "welcome to staging server"
  db:
    ip: 192.168.0.16
    port: 9999

---

spring:
  profiles: prod
  
msapconfig:
  greeting: "welcome to prod server"
  db:
    ip: 192.168.0.16
    port: 9999
